spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atd?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true
    username: root
    password: 1111
  data:
    redis:
      host: localhost
      port: 6379
      database: 5
      timeout: 60000
  thymeleaf:
    #prefix: classpath:/templates/
    suffix: .html

  jackson:
    serialization:
      write-dates-as-timestamps: true